development:
  adapter: mysql
  encoding: utf8
  # host: localhost
  # socket: /var/lib/mysql/mysql.sock
  database: rwd_development
  username: root
  password: 

production:
  adapter: mysql
  encoding: utf8
  # host: localhost
  # socket: /var/lib/mysql/mysql.sock
  database: rwd_production
  username: root
  password: 
